# Generated by Django 3.2.24 on 2024-05-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
