# Generated by Django 3.2.24 on 2024-03-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.collections'),
        ),
    ]
